fixup! release: add Mac OSX installer build
This switches to universal builds, i.e. binaries that contain both
x86_64 and arm64 parts. That way, the same `.pkg`/`.dmg` can be used on
Intel as well as on ARM Macs.

To that end, we are installing the Intel flavor of Homebrew on a
macOS/ARM runner, install the dependencies both in the Intel and ARM
flavor of Homebrew, and then use `lipo` to concoct universal versions of
the dependencies. Since we do not ship those dependencies anyway, things
work magically in the installed setups as long as the dependencies are
present there, too.

Note that for this hack to work, we no longer want to override the
`PATH` by prefixing `/usr/local/bin/` because `/usr/local/` is the home
of Homebrew's Intel variant only, not of the ARM variant (which calls
`/opt/homebrew/` its home). And in any case, Homebrew's `bin/` directory
is in the `PATH` of the runners we use, no need to be explicit about it.

Signed-off-by: Jeff Hostetler <jeffhostetler@github.com>
Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>

diff --git a/.github/workflows/build-git-installers.yml b/.github/workflows/build-git-installers.yml
--- a/.github/workflows/build-git-installers.yml
+++ b/.github/workflows/build-git-installers.yml
@@ -306,8 +306,6 @@ jobs:
     strategy:
       matrix:
         arch:
-          - name: x86_64
-            runner: macos-latest
           - name: arm64
             runner: macos-latest-xl-arm64
     runs-on: ${{ matrix.arch.runner }}
@@ -323,9 +321,19 @@ jobs:
 
       - name: Install Git dependencies
         run: |
-          set -x
+          set -ex
+
+          # Install x86_64 packages
+          arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+          arch -x86_64 /usr/local/bin/brew install gettext curl
+
+          # Install arm64 packages
           brew install automake asciidoc xmlto docbook
           brew link --force gettext
+
+          # Make universal gettext and curl library
+          lipo -create -output libintl.a /usr/local/opt/gettext/lib/libintl.a /opt/homebrew/opt/gettext/lib/libintl.a
+          lipo -create -output libcurl.dylib /opt/homebrew/opt/curl/lib/libcurl.4.dylib /usr/local/opt/curl/lib/libcurl.4.dylib
 
       - name: Set up signing/notarization infrastructure
         env:
@@ -383,24 +391,32 @@ jobs:
             exit 1
           }
 
-          # Configure the environment
+          # Trace execution, stop on error
           set -ex
-          PATH=/usr/local/bin:$PATH
-          export CURL_LDFLAGS=$(curl-config --libs)
 
           # Write to "version" file to force match with trigger payload version
           echo "${{ needs.prereqs.outputs.tag_version }}" >>git/version
 
-          # Configure the Git build to pick up gettext
-          homebrew_prefix="$(brew --prefix)"
+          # Configure universal build
           cat >git/config.mak <<EOF
-          LDFLAGS = -L$homebrew_prefix/lib -L/usr/local/opt/gettext/lib
-          CFLAGS = -I$homebrew_prefix/include -I/usr/local/opt/gettext/include
+          # Create universal binaries. HOST_CPU is a bit of a lie and only
+          # used in 'git version --build-options'.  We'll fix that in code.
+          HOST_CPU = universal
+          BASIC_CFLAGS += -arch arm64 -arch x86_64
           EOF
 
-          # On Apple Silicon, homebrew apparently does not install a `gcc` symlink
-          test x86_64 = '${{ matrix.arch.name }}' ||
-          echo 'CC = gcc-13' >>config.mak
+          # Configure the Git build to pick up gettext
+          homebrew_prefix="$(brew --prefix)"
+          cat >>git/config.mak <<EOF
+          CFLAGS = -I$homebrew_prefix/include -I/usr/local/opt/gettext/include
+          LDFLAGS = -L"$(pwd)"
+          EOF
+
+          # Configure the Git build to pick up the universal `libcurl.dylib`
+          cat >>git/config.mak <<EOF
+          CURL_LDFLAGS := -L"$(pwd)" -lcurl
+          CURL_CONFIG := /usr/bin/true
+          EOF
 
           # Avoid even building the dashed built-ins; Those should be hard-linked
           # copies of the `git` executable but would end up as actual copies instead,
@@ -424,7 +440,7 @@ jobs:
           make -C git/.github/macos-installer V=1 payload
 
           # Codesign payload
-          cp -R stage/git-${{ matrix.arch.name }}-$VERSION/ \
+          cp -R stage/git-universal-$VERSION/ \
             git/.github/macos-installer/build-artifacts
           make -C git/.github/macos-installer V=1 codesign \
             APPLE_APP_IDENTITY="$A3" || die "Creating signed payload failed"
